project:
  type: website
  output-dir: docs
format:
  html:
    theme: solar
    toc: true
    toc-location: left
editor: visual

website:
  title: "PISCES"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Contextualization"
        href: contextualization.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Team"
        href: team.qmd
      - text: "Aulas"
        href: aulas.qmd
